#! /bin/sh
rules="$HOME/.makerules"

for ft in $@; do
  for f in *; do
    nf="$(awk -F. '{print $1}' <<<"$f").$ft"

    make -f "$rules" -n -s "$nf" 1>/dev/null 2>/dev/null
    if [ $? -eq 0 ]; then
      make -s -f "$rules" "$nf" 
    fi
    
  done
done
